### ISSUE TITLE
How to use edges as paths for animation

### ISSUE THREAD

**Issue by AlbertoCastelo** [tylingsoft/dagre-d3-renderer#1]
I'm trying to build a app where to show SVG object (a square,  for instance) moving along the path of a graph. I know the edge (my path) is built as interpolation between 2 points. How can I recover those points from dagre?

**Comment by tylerlong** [comment]
For now you'd better ask this question in https://github.com/cpettitt/dagre-d3 instead.

I just created this repo and I didn't change its feature set. To be frank I am not very familiar with its usage.
