### ISSUE TITLE
Upgrade to d3 v4.x?

### ISSUE THREAD

**Issue by den1k** [tylingsoft/dagre-d3-renderer#2]
What's in the way of upgrading d3?

**Comment by tylerlong** [comment]
It's in the todo list but I don't actually have time to do it.

Mainly because I am not very familiar with D3.

This project is based on the dagre-d3 project. I upgraded it to ES6  and webpack. I didn't change any of its logic due to lack of D3 knowledge.

**Comment by tylerlong** [comment]
Some one else has done the work: https://github.com/smbolton/dagre-d3v4

Maybe I can reference his work and update this project.

**Comment by lutzroeder** [comment]
The main fork of dagre-d3 got moved to a GitHub organization at https://www.github.com/dagrejs and now supports D3.js v4. It would be great if you can give it a try. Also, trying to find ways to consolidate the changes made in different places. Do you have any recommendations how to approach this?

**Comment by tylerlong** [comment]
The work has been done.
